### ISSUE TITLE
Named semaphore size limit on OSX

### ISSUE THREAD

**Issue by rleonid** [UnixJunkie/parany#12]
turns out to be a bit short: [PSEMNAMLEN](https://github.com/st3fan/osx-10.9/blob/master/xnu-2422.1.72/bsd/sys/posix_sem.h#L54).

Can we `s/ocaml_//` [here](https://github.com/UnixJunkie/parany/blob/master/parany.ml#L25) ?
Or maybe (or also) change `pid` to `p` and `sem` to `s` ?

**Comment by UnixJunkie** [comment]
feel free to submit a patch
