### ISSUE TITLE
add ~init and ~finalize optional functions to workers, as I did in parmap

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/parany#22]

**Comment by UnixJunkie** [comment]
@mseri if you are looking for a simple contribution to parany, this one would be a good candidate.

**Comment by JuliaLawall** [comment]
I would also like this option.  Also Parmap.redirect.

**Comment by UnixJunkie** [comment]
Ok for init and finalize; good to know what other users really need.
For Parmap.redirect, you should have opened another issue.
Unfortunately, I don''t think I will implement that one, because I don't like Parmap.redirect's semantic (using a core [id] instead of an identifier of the owning process: parany doesn't do core pinning by default) and it it some setup
that a worker process should do in its ~init function.

**Comment by UnixJunkie** [comment]
Wish granted.
User-provided init/finalizers will be supported in the next major release in opam (should be v12.0.0).
Tell me how it goes.

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-repository/pull/18173

**Comment by JuliaLawall** [comment]
Wonderful, thanks.
