### ISSUE TITLE
Bus error?

### ISSUE THREAD

**Issue by JuliaLawall** [UnixJunkie/parany#49]
I get a lot of bus errors.  I see that I also have only 1 or 2 cores running my code, while I asked for 44.  Is this a known problem?

**Comment by UnixJunkie** [comment]
I never saw this.
How many physical cores does the machine have?
How many tasks (jobs list length) do you have and what is the chunk size you are using?
Try csize=1 first (tweak csize later only if it make things go faster).
Can you show me a stack trace?
Do you have an example I could run myself?
If some workers are crashing, they are not restarted, so at some point you may have no process left working for your (though parany >= v12.0.1 should terminate cleanly even in that case).
If a job can fail, the work function should have type: ('a -> 'b option).
You should catch whatever exception can come, log properly what you want and return None in that case.
If you do like this, the rest of the computation should go on.

I use parany in production for very big calculations. I am not aware of any problem with it (except that the performance should be lower on osx and BSDs compared to Linux; this is tracked here: https://github.com/UnixJunkie/parany/issues/44).

**Comment by UnixJunkie** [comment]
PS: I don't even know how to produce a bus error in ocaml

**Comment by JuliaLawall** [comment]
There was an error that caused multiple threads to be writing to the same file.  I didn't track down the reason for the Bus error, but just fixed this problem.  The Bus error is surely unrelated to parany, so I'll close this issue.
