### ISSUE TITLE
duplicated i/o

### ISSUE THREAD

**Issue by JuliaLawall** [UnixJunkie/parany#50]
Perhaps this is considered to be a feature rather than a bug, but i/o that has not been flushed before calling eg Parany.Parmap.parmap occurs multiple times, which is at least confusing.

**Comment by UnixJunkie** [comment]
The workaround is to flush stdin and stderr before calling any parany function.
Currently, we just do a Gc.compact() prior to forking.

**Comment by UnixJunkie** [comment]
One possible fix is to call flush_all() before Gc.compact() in parany's code.
Would that suit you?

**Comment by JuliaLawall** [comment]
On Wed, 24 Feb 2021, Francois Berenger wrote:

>
> One possible fix is to call flush_all() before Gc.compact() in parany's
> code.
> Would that suit you?

Seems fine for me.  For the moment I am just calling flush stdout and
flush stderr before each parany call (and at the end of each parany
function).

julia

**Comment by UnixJunkie** [comment]
This is a quite reasonable request; I had to fix my own programs because of this duplicated I/O problem in the past
and I see that parmap uses flush_all, so I will do the same.

**Comment by UnixJunkie** [comment]
Ok, corrected since v12.0.3; should be available in opam soon.

**Comment by JuliaLawall** [comment]
On Thu, 25 Feb 2021, Francois Berenger wrote:

>
> Ok, corrected since v12.0.3; should be available in opam soon.

Thansk for all the help.

julia
