### ISSUE TITLE
try OCaml multicore (Domains?) backend

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/parany#55]

**Comment by nilsbecker** [comment]
@UnixJunkie conversely, it might be appreciated if you gave feedback on the domainslib parallel API, since you have experience with using/writing one? afaics things are not set in stone there yet

**Comment by UnixJunkie** [comment]
After years at writing scientific parallel programs, some in Python but most in OCaml, my opinion
is that the ultimate interface for scientific parallel programming for a multicore computer is the one offered by parany.
I strip it down here:
```ocaml
val run:
  ?csize:int ->
  ~nprocs: int ->
  demux:(unit -> 'a) ->
  work:('a -> 'b) ->
  mux:('b -> unit) -> unit
```

This is a generalization of the "Google map-reduce".
You need an unfold/demux function, so that there are items to map/work on in parallel, then
a reduce/mux function so that you can gather the results.
The chunk-size parameter (csize) allows to tweak the granularity of the computation, so
that you can optimize performance for the computer at hand.
The nprocs parameter allows to limit how many cores you use.

**Comment by nilsbecker** [comment]
thanks!

**Comment by nilsbecker** [comment]
Out of curiosity i made this (probably too naive) domainslib backend implementation of `Parany.run`; see below. It works on cursory testing. I can see a few problems
- does out-of-order accumulation by `mux` make sense in this context?
-  core pinning seems to be unavailable
- it's not clear to me if the `init` and `finalize` functions have a role in the absence of child processes.

```ocaml
open Domainslib

exception End_of_input

let (|?) o default = Option.value ~default o

let run
    ?init
    ?finalize
    ?preserve
    ?core_pin
    ?csize
    n_cores
    ~demux
    ~work
    ~mux =
  let core_pin = core_pin |? false
  and preserve = preserve |? false in
  if core_pin || not preserve
  then raise (Invalid_argument
                "core pinning and out-of-order collection are not implemented")
  else
    let csize = csize |? 1
    and init = init |? fun _i -> ()
    and finalize = finalize |? fun () -> () in
    let pool = Task.setup_pool ~num_additional_domains:(n_cores - 1) in
    let revlist = ref [] in
    (* we have to create all inputs eagerly first in order to be able to
     * observe the End_of_input. *)
    let rec input_queues i =
      let revlist' = ref [] in
      try for _ = 1 to csize do
          revlist' := demux () :: !revlist' done;
        revlist := (i, !revlist') :: !revlist ;
        input_queues (succ i)
      with End_of_input ->
        revlist := (i, !revlist') :: !revlist in
    let work_queues () =
      List.rev_map (fun (i, rlist') ->
          Task.async pool (fun () ->
              init i;
              (* work is performed in forward order and the list is reversed
               * afterwards in List.rev_map, but evaluation order is not
               * guaranteed anyway. *)
              let result = List.rev_map work rlist' in
              finalize (); result))
        !revlist in
    let collect p =
      let l = Task.await pool p in
      List.iter mux l in
    input_queues 0; work_queues () |> List.iter collect
```

**Comment by nilsbecker** [comment]
This was my test:
```ocaml
let max_iterations = 37
let iterations = ref 0
let results_rlist = ref []
let demux () = incr iterations; if !iterations <= max_iterations then !iterations
  else raise Parany.End_of_input
let work i = Unix.sleepf 0.0; print_int i; print_newline (); flush_all (); i
let init i = Unix.sleepf (Random.float 0.4); Printf.printf "chunk %d\n" i; flush_all ()
let finalize () = Printf.printf "worker done\n"; flush_all ()
let mux i = results_rlist := i :: !results_rlist
let csize = 3
let preserve = true
let _ = Parany.run 4 ~preserve ~csize ~demux ~work ~mux ~init ~finalize
let _ = print_newline ()
let _ = Format.(printf "all results in order: %a"
                  (pp_print_list ~pp_sep:pp_print_space pp_print_int)
                  (List.rev !results_rlist))
```

**Comment by UnixJunkie** [comment]
> Out of curiosity i made this (probably too naive) domainslib backend implementation of `Parany.run`; see below. It works on cursory testing. I can see a few problems
> 
>     * does out-of-order accumulation by `mux` make sense in this context?

In parany, I default to giving results in a random order because this is usually faster
than giving them in the same order than input order.

>     * core pinning seems to be unavailable

I want to get rid of it; in my experience it has no significant performance gain.
It would remove an annoying/dirty dependency (cpu) from the parany opam package.

>     * it's not clear to me if the `init` and `finalize` functions have a role in the absence of child processes.

You can ignore those for the moment.
They are not super useful (some people use those when they want to do some per-worker logging setup, etc).

**Comment by UnixJunkie** [comment]
Parany is supposed to work even if all jobs cannot be loaded into memory at once.
I am not sure your proposed implementation allows that.

**Comment by nilsbecker** [comment]
i'm not sure either. my problem was that when i submit a job by something like `Task.async (fun () -> let input = demux () in work_on input` then the exception `End_of_input` would be raised in the child domain, which i thought is not what is needed? i then resorted to a list of inputs in the parent domain. 

but maybe one can be cleverer. maybe a first work queue of `demux` jobs which then lauch the actual `work` jobs unless `End_of_input` occurs. hmm.

**Comment by nilsbecker** [comment]
> Parany is supposed to work even if all jobs cannot be loaded into memory at once.

actually, could you elaborate a bit about what must/need not fit into memory? here are my thoughts:

each call of demux produces an input value; is the requirement that the full list of inputs may not fit into memory? if so, then i think at least n_proc inputs must fit into memory anyway since they are supposed to be processed in parallel. if csize > 1 i think at least csize * nproc would need to fit, correct? 

or is the outputs generated by mux that may not fit simultaneously? that seems the least problem. as mux is sequential, one output can be stored away to disk at a time.

or the memory required by each work job? i think that only n_proc work jobs run at the same time, but each output of type 'b would sit inside its (fulfilled) 'b Task.promise after completion. depending on how fast mux consumes the promises and frees memory, it could be that  more than n_proc of those values are in memory at the same time. is that the problem?

**Comment by UnixJunkie** [comment]
Basically, some people use Parany because Parmap is not applicable.
Parmap: you have an array or a list of jobs, you want to map in parallel on them (to accelerate things).
Parany: there are potentially too many jobs --> it is impossible to load all of them into a list or array (would blow up memory).

To implement parany using multicore OCaml, I feel there should be two channels/streams.
One thread should fill the jobs stream by calling demux() until End_of_input.
Workers should fill the results stream by working on jobs taken from the jobs stream.
The muxer thread should unpile the reults stream.

So: one demuxer thread, one muxer threads, n worker threads.
You need a stream/channel datastructure so that values can be passed between threads.

**Comment by nilsbecker** [comment]
here is another version. now chunks of input (`work_packages`) are generated at once and submitted to the worker queue; they are processed as cores become available and should be immediately consumed by the mux function via `collect`; collected results should be gc'd after mux is done, as the results queue is consumed on the fly.  at least that's what i think happens ;)


```ocaml
open Domainslib

exception End_of_input
type 'a chunk = Intermediate of 'a Queue.t | Last of 'a Queue.t

let run
    ?csize
    n_cores
    ~demux
    ~work
    ~mux =
  let csize = Option.value ~default:1 csize in

  let pool = Task.setup_pool ~num_additional_domains:(n_cores - 1) in
  let results = Queue.create () in

  let input_task () =
    let work_package = Queue.create () in
    try
      for _ = 1 to csize do
        Queue.push (demux ()) work_package done;
      Intermediate work_package
    with End_of_input ->
      Last work_package in
  let add_job work_package =
    let job = Task.async pool (fun () ->
        Queue.to_seq work_package |> Seq.map work |> Queue.of_seq) in
    Queue.push job results in
  let rec process_all () =
    match input_task () with
    | Intermediate wp -> add_job wp; process_all ()
    | Last wp -> add_job wp in

  let collect job =
    let finished_job = Task.await pool job in
    Queue.iter mux finished_job in

  process_all ();
  try while true do collect (Queue.pop results) done
  with Queue.Empty -> ()
```

**Comment by nilsbecker** [comment]
PS. i would have liked `run n_cores` to evaluate partially, constructing a Task.pool for later reuse. unfortunately that seems to be impossible due to the requirements for optional arguments to be followed by positional ones. it is possible to make `run ~csize ncores` evaluate partially 
```ocaml
let run
    ?csize
    n_cores =
  let csize = Option.value ~default:1 csize in
  let pool = Task.setup_pool ~num_additional_domains:(n_cores - 1) in
  fun
    ~demux
    ~work
    ~mux -> ...
```
but that also fixes the chunk size. might still be useful?

**Comment by nilsbecker** [comment]
actually, i'm getting weird nondeterministic output with the above. i don't get it. either i did something stupid with the mutable queues or there is a bug in domainslib.

**Comment by UnixJunkie** [comment]
I might try to implement something based on your last trial. The code is quite small so that's interesting.

**Comment by UnixJunkie** [comment]
With the fork-based version of parany:
```
# time diff <(seq 0 99999)      <(_build/default/src/test.exe $NPROCS 1 0 2>/dev/null | sort -n)
real    0m3.964s
user    0m1.017s
sys     0m2.569s
```
With the ocaml-multicore version:
```
time diff <(seq 0 99999)      <(_build/default/src/test.exe $NPROCS 1 0 2>/dev/null | sort -n)

real    0m0.290s
user    0m0.617s
sys     0m0.430s

```
I am on a 8 threads CPU.
That's an acceleration of ~13.7x on a stupid benchmark !

**Comment by UnixJunkie** [comment]
The code is in the 'domains' branch.

**Comment by UnixJunkie** [comment]
@nilsbecker It is almost feature complete now, you can give it a try.

**Comment by nilsbecker** [comment]
> I might try to implement something based on your last trial

The caveat being that my last trial appears to be buggy! Be sure to check that the output is in fact correct...

**Comment by nilsbecker** [comment]
i had a look at your new version -- it's using channels instead of promises, which sounds like it could avoid errors coming from processing lists with finished or unfinished jobs in them in the main thread (i still don't know what's actually wrong in my version). 

one thing i didn't get in your version was this: upon seeing End_of_input, the demux loop sends n_proc empty arrays to the  job queue. but afaict it's not garantueed that each [||] will be processed by a different worker. e.g. all workers but one could be still busy while the last worker processes all of the [||] in a row (correct?). 

if this is correct, first, it's not clear that you need to send n_proc [||]'s instead of just one? also it seems possible that the muxer loop would conclude all work is done and exit while some workers are still busy? in effect not all work will be collected?

**Comment by nilsbecker** [comment]
the buggy behavior in my version appears to be resolved when using the current domains+effects multicore development branch.

**Comment by UnixJunkie** [comment]
Since a worker processes one jobs array at a time, and will stop after a single empty array have been seen, this correctly stops workers.
My version have been tested, if it was not correct, I would already know about it.
When you work on parany, there is a 'make test' target.

**Comment by nilsbecker** [comment]
ok, i think i finally get it. in https://github.com/UnixJunkie/parany/blob/c9e7a514c6eb8a63eb8f5691496b5cd8d17304c0/src/parany.ml#L14 the worker domain exits after receiving one `[||]`. that makes total sense! i had read the code as if it would recurse again, so that the loop would consume all empty arrays right away. great! also it's neat that there is such a speedup!

**Comment by UnixJunkie** [comment]
Notice that the speedup just indicates that multicore OCaml has less overhead.
This test code is not an interesting benchmark; just some parallel computation that allows to test things are working,
with various combinations of csize, preserve and nprocs.

**Comment by nilsbecker** [comment]
> speedup just indicates that multicore OCaml has less overhead.

true. it may be interesting to see if the multicore backend can speed up workloads where data is shared between parallel threads -- cases where the forking based solutions resort to marshalling or memmapped arrays.

**Comment by UnixJunkie** [comment]
cf. https://github.com/UnixJunkie/parany/tree/domains

**Comment by UnixJunkie** [comment]
I will do a major release for ocaml-5 soon.
