### ISSUE TITLE
build/test/random numbers failure with dune 3.6.0

### ISSUE THREAD

**Issue by nilsbecker** [UnixJunkie/parany#59]
I am trying to use Parany in a project that builds fine without. After minor modifications to one executable source code to use Parany and adding parany to the `libraries` field in the dune file for this executable, I call `dune build` and get:
```
Fatal error: exception Sys_error("/var/folders/07/_zztv_tn58g0np7xzsd2fv5800011n/T/build_1457a7_dune/iparany_ffaba: No such file or directory")
```
repeated several times. Not sure who/what is responsible...

ocaml 4.14.0, current parany, current macos

**Comment by nilsbecker** [comment]
Some more info. 

Since this is a test, I also tried `dune runtest`. This succeeds as expected if i specify the `~cores:1` for the `Parany.run` call in the test program. If I specify some higher value, I get empty results from the `work` functions. Likewise, `dune build` succeeds when `cores` is 1. 

So it seems this is a runtime problem not a build problem as I originally thought. 

It may be connected to the use of the GSL random number generator in the worker processes. Is that supported? Currently I seed the GSL rng within each worker function via the supplied worker function argument. Do I need to create a new rng instance within each worker?

**Comment by UnixJunkie** [comment]
Looks like you are on a Mac, and temporary files are not created in /tmp.

**Comment by UnixJunkie** [comment]
Nothing to do with your RNG, I think.
If you want to give a try at a fix: try to change the two Filename.temp_file calls in parany.ml to use ~temp_dir:"/tmp".
If it works, please let me know and send a PR.

**Comment by UnixJunkie** [comment]
Explanation, when cores>1, some temp files are needed at runtime.
If cores=1, this is not necessary.

**Comment by nilsbecker** [comment]
yes! see pr.

**Comment by UnixJunkie** [comment]
corrected by https://github.com/UnixJunkie/parany/pull/60

**Comment by UnixJunkie** [comment]
I have tagged v12.2.1 which includes your fix.
It should allow people to update the package in opam, if nobody does it before I return to work on Monday.

**Comment by UnixJunkie** [comment]
Should land in opam soon; https://github.com/ocaml/opam-repository/pull/22574

**Comment by nilsbecker** [comment]
Alas, writing to `/tmp` appears to be forbidden on some linux systems used in CI. FWIW, macos defines `$TMPDIR` but also has a per-user tmp directory in `~/Library/Caches/TemporaryItems/`.

**Comment by UnixJunkie** [comment]
Testing a parallel library in a CI environment is special.
I am already happy if they allow us to use more than one core.
And I don't care about those CI things.
I release working software; it just annoys me.
