### ISSUE TITLE
fork-based version for ocaml-5

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/parany#70]

**Comment by UnixJunkie** [comment]
at least in a specific branch, probably starting from a previous version (like the one currently shipped for ocaml<5)

**Comment by UnixJunkie** [comment]
the old version can probably still install and run; however in that case the two versions cannot be co-installed

**Comment by UnixJunkie** [comment]
ok, versions <13.0 are fork-based.

**Comment by UnixJunkie** [comment]
@mseri (or any interested user, by the way) do you have some idea on how I could make the fork-based and thread-based versions co-exist?
Ideally, I would like users to be able to install both versions at the same time.
However, in their program, they should be able to choose which runtime behavior they want.
Maybe, I create two modules: Parany.Fork and Parany.Thread; both having the same interface ?
There might be some code duplication if I do that, that's the thing I don't like currently.

**Comment by UnixJunkie** [comment]
Maybe @JuliaLawall or @thierry-martinez may have some thoughts also.

**Comment by UnixJunkie** [comment]
One possible drastic solution: drop the thread-based version.

**Comment by mseri** [comment]
I think you can use https://dune.readthedocs.io/en/stable/variants.html to create a unique interface and then, depending on what you link, fix the runtime. It may help reduce duplication. I personally don't like setting the runtime with a global variable as done in Lwt, but that could also be an option to reduce duplication.

**Comment by JuliaLawall** [comment]
Thanks for the forward. I don't have a preference between fork and thread.

**Comment by UnixJunkie** [comment]
@JuliaLawall they will have different parallelization performance (depending on your application); you might want to benchmark and then stick to the implementation with the best performance.
parany < v13 is fork-based; >= v13 is thread-based and ocaml>=5.0.0.
So currently, you can install a given parany version to make that choice.
In the future, I would like the two possibilities to co-install, so not using the parany version number trick.

**Comment by UnixJunkie** [comment]
@mseri I did not know this dune hack, but I will probably do something simpler and not relying on a dune feature.

**Comment by UnixJunkie** [comment]
tracked by https://github.com/UnixJunkie/parany/issues/72
